### ISSUE TITLE
Action: To Pasteboard as Markdown

### ISSUE THREAD

**Issue by prat0088** [ksalzke/completed-task-report-omnifocus-plugin#2]
Thank you for this plugin!  It's wonderful to see the continued development.  

It would be handy to have an action included with the plugin that exports the list to the pasteboard as markdown.  At least for me, since I have my own Day One templates I want to paste the list of tasks into, or just into Text Edit to verify.

**Comment by ksalzke** [comment]
This should be fairly straightforward to do. 

I have uni exams and a 5-month old so it won't happen straight away, but I'll pop this on my list and expect I should get to it within the next month. Thanks for the suggestion!

**Comment by ksalzke** [comment]
Actually I managed to sneak this in during naptime - code and README both updated but it should just show up as another option in the menu. It's relatively untested, so give it a try and let me know if it's working okay for you, or if there are any issues!

**Comment by prat0088** [comment]
I just got time to install the latest version and try it out.  Works great.  Thank you!
